AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Personal Website - Backend API Only'

Parameters:
  Stage:
    Type: String
    Default: prod
    Description: Deployment stage

Resources:
  # DynamoDB Table
  VisitorCountsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "VisitorCounts-Backend-${Stage}"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
      Tags:
        - Key: Environment
          Value: !Ref Stage

  # Lambda Function
  VisitorCounterFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "visitor-counter-backend-${Stage}"
      CodeUri: ../backend/target/personal-site-api-1.0.0.jar
      Handler: dev.baotrinh.personal_site_api.VisitorCounterHandler::handleRequest
      Runtime: java21
      Timeout: 30
      MemorySize: 512
      Environment:
        Variables:
          VISITOR_COUNTS_TABLE: !Ref VisitorCountsTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref VisitorCountsTable
      Events:
        VisitApi:
          Type: HttpApi
          Properties:
            Path: /visit
            Method: post
            ApiId: !Ref VisitorCounterApi

  # API Gateway
  VisitorCounterApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: !Ref Stage
      CorsConfiguration:
        AllowOrigins:
          - "https://baotrinh.dev"
          - "https://www.baotrinh.dev"
          - "*"
        AllowHeaders:
          - "Content-Type"
        AllowMethods:
          - POST
          - OPTIONS

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${VisitorCounterApi}.execute-api.${AWS::Region}.amazonaws.com"
    
  TableName:
    Description: "DynamoDB table name"
    Value: !Ref VisitorCountsTable