AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Personal Website - Simplified for Cloudflare DNS'

Parameters:
  Stage:
    Type: String
    Default: prod
    Description: Deployment stage

Resources:
  # DynamoDB Table
  VisitorCountsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "VisitorCounts-Cloudflare-${Stage}"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      Tags:
        - Key: Environment
          Value: !Ref Stage
        - Key: Component
          Value: Backend

  # Lambda Function
  VisitorCounterFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "visitor-counter-${Stage}"
      CodeUri: ../backend/target/personal-site-api-1.0.0.jar
      Handler: dev.baotrinh.personal_site_api.VisitorCounterHandler::handleRequest
      Runtime: java21
      Timeout: 30
      MemorySize: 512
      Environment:
        Variables:
          VISITOR_COUNTS_TABLE: !Ref VisitorCountsTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref VisitorCountsTable
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${AWS::StackName}-visitor-counter-${Stage}*"
      Events:
        VisitApi:
          Type: HttpApi
          Properties:
            Path: /visit
            Method: post
            ApiId: !Ref VisitorCounterApi
      Tags:
        Environment: !Ref Stage
        Component: Backend

  # API Gateway
  VisitorCounterApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: !Ref Stage
      CorsConfiguration:
        AllowOrigins:
          - "https://baotrinh.dev"
          - "https://www.baotrinh.dev"
          - "*"
        AllowHeaders:
          - "Content-Type"
          - "X-Amz-Date"
          - "Authorization"
          - "X-Api-Key"
          - "X-Amz-Security-Token"
        AllowMethods:
          - GET
          - POST
          - OPTIONS
        AllowCredentials: false
        MaxAge: 300
      Tags:
        Environment: !Ref Stage
        Component: Backend

  # S3 Bucket for Static Website
  WebsiteS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "baotrinh-dev-website-${AWS::AccountId}-${Stage}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: DeleteIncompleteUploads
            Status: Enabled
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 1
          - Id: DeleteOldVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: 30
      Tags:
        - Key: Environment
          Value: !Ref Stage
        - Key: Component
          Value: Frontend

  # CloudFront Origin Access Control
  WebsiteOriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub "${AWS::StackName}-OAC"
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  # S3 Bucket Policy
  WebsiteS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteS3Bucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub "${WebsiteS3Bucket}/*"
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${WebsiteCloudFrontDistribution}"

  # Security Headers Response Policy
  SecurityHeadersResponsePolicy:
    Type: AWS::CloudFront::ResponseHeadersPolicy
    Properties:
      ResponseHeadersPolicyConfig:
        Name: !Sub "${AWS::StackName}-SecurityHeaders"
        SecurityHeadersConfig:
          StrictTransportSecurity:
            AccessControlMaxAgeSec: 31536000
            IncludeSubdomains: true
            Override: false
          ContentTypeOptions:
            Override: false
          FrameOptions:
            FrameOption: DENY
            Override: false
          ReferrerPolicy:
            ReferrerPolicy: strict-origin-when-cross-origin
            Override: false

  # CloudFront Distribution
  WebsiteCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: !Sub "Personal Website - ${Stage}"
        DefaultRootObject: index.html
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt WebsiteS3Bucket.RegionalDomainName
            OriginAccessControlId: !Ref WebsiteOriginAccessControl
            S3OriginConfig:
              OriginAccessIdentity: ""
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          Compress: true
          CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad  # CachingDisabled for SPA
          ResponseHeadersPolicyId: !Ref SecurityHeadersResponsePolicy
        CacheBehaviors:
          - PathPattern: "/static/*"
            TargetOriginId: S3Origin
            ViewerProtocolPolicy: redirect-to-https
            Compress: true
            CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6  # CachingOptimized
            ResponseHeadersPolicyId: !Ref SecurityHeadersResponsePolicy
          - PathPattern: "/assets/*"
            TargetOriginId: S3Origin
            ViewerProtocolPolicy: redirect-to-https
            Compress: true
            CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6  # CachingOptimized
            ResponseHeadersPolicyId: !Ref SecurityHeadersResponsePolicy
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
        PriceClass: PriceClass_100
      Tags:
        - Key: Environment
          Value: !Ref Stage
        - Key: Component
          Value: Frontend

  # Deployment Role for CI/CD
  DeploymentRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AWS::StackName}-DeploymentRole"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
          - Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action: sts:AssumeRole
      Policies:
        - PolicyName: S3DeploymentPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:ListBucket
                  - s3:GetBucketLocation
                Resource: !Sub "${WebsiteS3Bucket}"
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:PutObjectAcl
                  - s3:GetObject
                  - s3:DeleteObject
                Resource: !Sub "${WebsiteS3Bucket}/*"
              - Effect: Allow
                Action:
                  - cloudfront:CreateInvalidation
                  - cloudfront:GetInvalidation
                  - cloudfront:ListInvalidations
                Resource: !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${WebsiteCloudFrontDistribution}"
      Tags:
        - Key: Environment
          Value: !Ref Stage
        - Key: Component
          Value: Deployment

Outputs:
  # Backend Outputs
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${VisitorCounterApi}.execute-api.${AWS::Region}.amazonaws.com"
    Export:
      Name: !Sub "${AWS::StackName}-ApiUrl"
    
  TableName:
    Description: "DynamoDB table name"
    Value: !Ref VisitorCountsTable
    Export:
      Name: !Sub "${AWS::StackName}-TableName"

  # Frontend Outputs
  S3BucketName:
    Description: "S3 bucket for website hosting"
    Value: !Ref WebsiteS3Bucket
    Export:
      Name: !Sub "${AWS::StackName}-S3Bucket"

  CloudFrontDistributionId:
    Description: "CloudFront distribution ID"
    Value: !Ref WebsiteCloudFrontDistribution
    Export:
      Name: !Sub "${AWS::StackName}-CloudFrontId"

  CloudFrontDomainName:
    Description: "CloudFront distribution domain name"
    Value: !GetAtt WebsiteCloudFrontDistribution.DomainName
    Export:
      Name: !Sub "${AWS::StackName}-CloudFrontDomain"

  WebsiteURL:
    Description: "Website URL via CloudFront"
    Value: !Sub "https://${WebsiteCloudFrontDistribution.DomainName}"
    Export:
      Name: !Sub "${AWS::StackName}-WebsiteURL"

  # Deployment Outputs
  DeploymentRoleArn:
    Description: "IAM role for deployment automation"
    Value: !GetAtt DeploymentRole.Arn
    Export:
      Name: !Sub "${AWS::StackName}-DeploymentRole"

  # Configuration for Frontend
  FrontendConfig:
    Description: "Frontend environment configuration"
    Value: !Sub |
      {
        "apiUrl": "https://${VisitorCounterApi}.execute-api.${AWS::Region}.amazonaws.com",
        "stage": "${Stage}",
        "cloudfrontDomain": "${WebsiteCloudFrontDistribution.DomainName}",
        "s3Bucket": "${WebsiteS3Bucket}"
      }
    Export:
      Name: !Sub "${AWS::StackName}-FrontendConfig"